### ISSUE TITLE
Enhance README, support ExtendScript debugger

### ISSUE THREAD

**Issue by lsh246** [shawnpyle/jasminejsx#1]
@shawnpyle I have some suggestions for the README file to clarify it. I also found that I needed to make one change to line 7 of test/run.jsx to get it to run from ExtendScript Debugger:

`if (typeof arguments !== 'undefined' && arguments && arguments.length > 0) { //load specified files`

Happy to open a pull request with my suggestions if you want to give me permission.

Thanks!

**Comment by shawnpyle** [comment]
You're welcome to clone the repository and then do a pull request from there. No permissions needed!
